### ISSUE TITLE
Update slides for Python

### ISSUE THREAD

**Issue by walshbr** [humanitiesprogramming/humanitiesprogramming.github.io#22]
- [x] Concepts 1 
- [x] Concepts 2
- [x] Concepts 3
- [x] Review 1
- [x] Review 2
- [ ] Review 3

Can start from there. I wouldn't overwrite them. Rather, copy the files and start replacing stuff. I can do the theoretical bits about Python or help with any parts that are too complicated for you. Will also need to update the slides repo. - https://github.com/humanitiesprogramming/slides/issues/1

**Comment by reedeth** [comment]
Have updated Concepts 1 and Review 1!

**Comment by reedeth** [comment]
Have updated Concepts 2 and Review 2!
