### ISSUE TITLE
Rebrand Git Tutorial w/o HTML/CSS

### ISSUE THREAD

**Issue by walshbr** [humanitiesprogramming/humanitiesprogramming.github.io#58]
Since we're not doing HTML/CSS this year

**Comment by reedeth** [comment]
All done! Closed with

https://github.com/humanitiesprogramming/humanitiesprogramming.github.io/commit/741fdbc87bb8ad43c8af8637f16a7245354f0cc6

and 

https://github.com/humanitiesprogramming/humanitiesprogramming.github.io/commit/7eb08760e5cf0988e88eb0ae996badc64a264b8c
