### ISSUE TITLE
Update positions for our bios

### ISSUE THREAD

**Issue by walshbr** [humanitiesprogramming/humanitiesprogramming.github.io#85]
We've both changed jobs

- [x] Brandon bio
- [x] Ethan bio

**Comment by walshbr** [comment]
@reedeth - I think you have a lot of things that you've done that aren't represented here. You might as well list the kind of DH work you did on your fellowship project, the topic of your diss and your interests, and your new gig that you're starting.

**Comment by reedeth** [comment]
Done!
