### ISSUE TITLE
Clearly articulate the connection to the real world

### ISSUE THREAD

**Issue by walshbr** [humanitiesprogramming/humanitiesprogramming.github.io#92]
- [x] Articulate learning objectives for each day
- [x] Show them case studies early on and describe the connection between what they're learning to those things. 
- [x] More practical, real-world examples that build on the work that we'll be doing together.

**Comment by reedeth** [comment]
I've done learning objectives for CLI, Git, Programming Concepts 1, and Programming Concepts 2!

**Comment by walshbr** [comment]
Did GitHub and added a real world case study to CLI. Also have case studies for GitHub

**Comment by walshbr** [comment]
Added real world stuff and connected case studies for prog concepts 1
